name: cached and loading
description: Blogging about tech stuffs
meta_description: "cached - tech blog by Roy Cockram"

markdown: kramdown
logo: false
paginate: 15
baseurl: "/"
domain_name: 'http://github.io'
google_analytics: 'UA-110577792-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'roy46.github.io'
author:         'Roy Cockram'

sass:
    style: compressed