name: General Tech Blog :)
description: Blogging about tech stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
logo: false
paginate: 15
baseurl: http://roy46.github.io/
domain_name: 'http://github.io'
google_analytics: 'UA-110577792-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'roy46.github.io'
author:         'Roy Cockram'
